### ISSUE TITLE
Google scholar referencing issues

### ISSUE THREAD

**Issue by MoayedHajiAli** [apoorvkh/cvpr-latex-template#9]
I have used this template for two of my papers and for both of them google scholar had issues parsing my references. In other words, my papers doesn't appear in the citations of the papers who I cited using this work. Semantic Scholar seems to parse it well. I am not super sure if the issue is with the template or not, that is why I am wondering if others had similar issues.

**Comment by apoorvkh** [comment]
Hey, thanks for your observation. I think it is common to see differences in the parsed citations between Google Scholar and Semantic Scholar, as they likely use different algorithms for parsing. I assume those algorithms are proprietary and so we aren’t able to say what the specific causes are.

Because S2 usually parses these well, the necessary information should indeed be present in the PDF and the problems are more likely with how Google Scholar parses, not with this template. In any case, this template inherits the bibliographic formatting entirely from the [official CVPR template](https://github.com/cvpr-org/author-kit), so you could consider following up there.

Hope that helps!
